Homework 1
rubyroidlabs/hexlet-2021 pull request #12
Opened 2021-04-01 10:49 UTC by kkrasilov

## Фамилия Имя
Красилов Константин

## Email
kkrasilov@gmail.com

## Номер домашнего задания
1

## Ссылка на видео с демо работы
https://youtu.be/6hLcNBGPt5o

## Комментарии
С метапрограммированием были проблемы
Буду еще читать по этой теме и ждать вебинар :)

2021-04-08 07:18 UTC, annvelents requested changes

2021-04-08 07:18 UTC, annvelents commented on Konstantin_Krasilov/1/about_asserts.rb
> +    actual_value = 1 + 1
(чтобы если поломалась функция `+`, ты это заметил)

2021-04-08 07:18 UTC, annvelents commented on Konstantin_Krasilov/1/about_scoring_project.rb
> +end
отличная реализация

2021-04-08 09:26 UTC, kkrasilov commented on Konstantin_Krasilov/1/about_class_methods.rb
> +  # Are there times you might prefer one over the other?
привет)
на практике я еще не использовал методы класса
но для одного метода наверное использовал бы `def self.method; end`, 
а для несольких методов или для определения приватных методов класса `class << self`
```
class Demo
  class << self
    def method; end 
    def method2; end 
  
    private

    def method3; end
  end
end
```

2021-04-08 09:59 UTC, kkrasilov commented on Konstantin_Krasilov/1/about_dice_project.rb
> +      assert value >= 1 && value <= 6, "value #{value} must be between 1 and 6"
пофиксил)
не вник в задачу сначала :)

2021-04-08 10:00 UTC, kkrasilov commented on Konstantin_Krasilov/1/about_iteration.rb
> +    # NOTE: 'map' is another name for the 'collect' operation
спасибо за всю информацию :)

2021-04-08 12:42 UTC, annvelents commented on Konstantin_Krasilov/1/about_class_methods.rb
> +  # Are there times you might prefer one over the other?
именно так и используется, верно

2021-04-08 16:55 UTC, annvelents requested changes

2021-04-08 16:55 UTC, annvelents commented on Konstantin_Krasilov/1/about_dice_project.rb
> +    number.downto(1) { @values << rand(DICE_EDGES) }
Лучше, но есть еще небольшая проблема:
https://apidock.com/ruby/Random/rand
`When max is an Integer, rand returns a random integer greater than or equal to zero and less than max`
так что у тебя в values значения от 0 до 5.
Любопытно, что тебе повезло, что тест с этим не упал)

2021-04-08 17:23 UTC, kkrasilov commented on Konstantin_Krasilov/1/about_dice_project.rb
> +    number.downto(1) { @values << rand(DICE_EDGES) }
ну тут тесты только из-за рандома не упадали) 
пофиксил!

2021-04-09 08:21 UTC, annvelents approved these changes

2021-04-09 08:21 UTC, merged

2021-04-09 08:53 UTC, annvelents commented on Konstantin_Krasilov/1/about_dice_project.rb
> +    number.downto(1) { @values << rand(DICE_EDGES) }
)) Класс)
и еще забыла написать, исправлять не нужно, вместо `number.downto(1)` можно использовать `number.times`

2021-04-09 09:08 UTC, kkrasilov commented on Konstantin_Krasilov/1/about_dice_project.rb
> +    number.downto(1) { @values << rand(DICE_EDGES) }
спасибо :)