Homework2
rubyroidlabs/hexlet-2021 pull request #36
Opened 2021-04-08 22:25 UTC by IlyaMur

## Фамилия Имя
Ilya Mur

## Email
ilyamur@hotmail.com

## Номер домашнего задания
2

## Ссылка на видео с демо работы
https://www.youtube.com/watch?v=ZE1PTzkp1ro

## Комментарии
Воспользовался ```HTTPparty```. Для тестов взял ```RSpec```. Запаковал в бандл.

Изначально сделал, чтобы класс ```RequestCollector``` собирал данные по всей базе, а затем в цикле main.rb выводил все запросы пачкой. Но смотреть на пустой экран и ждать вывода результатов оказалось скучно.
В результате, сделал постепенный вывод запросов, убрав цикл из ```main.rb``` и добавив сайд-эффект в лице ```puts``` в ```RequestCollector```. Теперь вывод идёт постепенно в консоль. Но можно и переделать обратно.
В main.rb получилось достаточно сложное ветвление, но элегантно упростить его не смог.

2021-04-08 23:20 UTC, warkann requested changes

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/lib/request.rb
> +    @time = args[:time]
Если какой либо из аргументов будет отсутствовать, то в переменной будет храниться `nil`. Например, в методе `.to_s` будет ошибка. В таких местах лучше сделать `args.fetch(:key, '')`

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +      begin
в данном случае `begin` не нужен т. к. у тебя уже есть блок `.each` и можно перехватывать ошибку на нем. 
```
resources.each do |resource|
....
rescue ...
...
end
```

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +  def initialize(requests)
этот метод лучше всего объявлять в самом верху, чтобы его было сразу видно и было понятно где искать

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +      requests << request
как ты смотришь, чтобы попробовать вместо заполнения массива всем запросами и позже в строке 33 перебирать массив 3 раза делать сразу хеш с тремя ключами `successed, failed, errored` и полем `total_requests`? тогда тебе можно будет сразу обращаться по ключам и не тратить время на перебор.

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +      requests << request
я бы попробовал для начала структуру примерно такую:
```
{
  total_requests: 1,
  successed: {
    request_count: 1,
    requests: [Request.new, ....]
  },
  ...
}

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/main.rb
> +  abort 'You must select a csv-file as an argument'
Имеет ли смысл, на твой взгляд, поместить  в баннер описание, что как аргумент требуется csv файл?

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/main.rb
> +
лишние пустые строки

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/main.rb
> +collection = if options.key?(:subdomains)
можно попробовать использовать `case` для этого ветвления

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/main.rb
> +collection = if options.key?(:subdomains)
Должна ли твоя логика обрабатывать только одну опцию? Как я вижу, у тебя выполнится какой-либо один ключ

2021-04-08 23:20 UTC, warkann commented on Mur_Ilya/2/spec/csv_reader_spec.rb
> +require 'csv_reader'
Пока не смотрел тесты, но уже вижу что у тебя проверяются только **положительные** (удачные, нацеленные на правильную работу) тесты и совсем нет **отрицательных** тестов на то, что ошибки будут обработаны, что при отсутствии нужных аргументов ситуация будет обработана и т. д.

2021-04-08 23:26 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +      begin
ты даже можешь делать
```
def some_method
...
rescue
...
ensure
...
end
```

Я думаю ты догадаешься, почему это возможно ;)

2021-04-08 23:39 UTC, IlyaMur commented on Mur_Ilya/2/Gemfile
> +git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
Это код, который генерит rspec))

2021-04-08 23:52 UTC, IlyaMur commented on Mur_Ilya/2/lib/request_collector.rb
> +      begin
```
resources.each do |resource|
  start_time = Time.now
  response = HTTParty.get("http://#{resource}/", { timeout: 1 })
  next unless response.body.include?(word)
  status = response.code
  time_string = "(#{((Time.now - start_time) * 1000).round}ms)"
  rescue StandardError => e
  status = "ERROR (#{e})"
end
```

Без begin и end код не работает корректно. Видимо, делаю что-то не так.

2021-04-08 23:58 UTC, IlyaMur commented on Mur_Ilya/2/lib/request_collector.rb
> +      requests << request
Тогда, получается и класс Request не нужен?  
В массив @requests RequestCollector'а будут складироваться хэши - ответы по запросам? Такая идея?

2021-04-08 23:59 UTC, IlyaMur commented on Mur_Ilya/2/main.rb
> +
Для читаемости оставил, рубокоп вроде пощадил.

2021-04-09 00:01 UTC, IlyaMur commented on Mur_Ilya/2/main.rb
> +collection = if options.key?(:subdomains)
Не очень понял как там с ```case```. Я думал про этот вариант.

2021-04-09 00:03 UTC, IlyaMur commented on Mur_Ilya/2/lib/request_collector.rb
> +  def initialize(requests)
Я руководствовался https://github.com/rubocop/ruby-style-guide

2021-04-09 00:24 UTC, warkann commented on Mur_Ilya/2/Gemfile
> +git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
но ты же умнее его ))

2021-04-09 00:27 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +      begin
что именно работает некорректно?

2021-04-09 00:32 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +      begin
И еще, тебе не кажется, что твой метод `send_requests` занимается слишком многим? и запросы посылает, и объекты создает и парсит строки.

2021-04-09 00:33 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +  def initialize(requests)
не видел раньше такого в стайлгайде, выглядит странно и неудобно. Но пускай

2021-04-09 00:36 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +      requests << request
А разве в данном случае объект не похож на хэш?) Мы так же можем иметь в классе нужные поля, мы может управлять логикой работы, можем иметь методы которые будут устанавливать и возвращать нужные нам значения в нужном виде

2021-04-09 00:37 UTC, warkann commented on Mur_Ilya/2/main.rb
> +
Даже когда у тебя 4 условия это смотрится странно и раздувает файл. А когда у тебя кода будет больше в разы? тогда у тебя файл будет от 1к+ строк?

2021-04-09 00:38 UTC, warkann commented on Mur_Ilya/2/main.rb
> +collection = if options.key?(:subdomains)
Ты прав, у тебя же хэш значений, тогда `case` отпадает. Остается вопрос по логике работы

2021-04-09 08:06 UTC, IlyaMur commented on Mur_Ilya/2/lib/request_collector.rb
> +      begin
Да, есть такое.

Но я не могу придумать как красиво вынести фильтр по слову. Ведь по сути мы там тоже шлём запрос и парсим тело ответа. Изначально даже пытался положить такой метод в CSVReader (фильтруем базу csv по слову на страницах, парся ответы), но там это совсем странно смотрелось.

Если  выносить отдельно, то получится х2 к запросам (сначала будет на поиск слова в body, потом на получение статуса ответа). 
В целом можно вынести аналог ``` next unless response.body.include?(word)``` в отдельный метод, но так ещё больше кода получится.

Объекты Request я уберу, puts там тоже необязателен. А вот как элегенатно поступить с фильтром - не придумал.

2021-04-09 08:30 UTC, IlyaMur commented on Mur_Ilya/2/main.rb
> +collection = if options.key?(:subdomains)
Сложность, что опции на входе достаточно разные. По сути они все обращаются к одному и тому же, но с разными входными условиями (фильтруем по слову, ничего не фильтруем, фильтруем по домену, по опенсорсу).

2021-04-09 08:44 UTC, IlyaMur commented on Mur_Ilya/2/lib/request_collector.rb
> +      begin
```
    resources.each do |resource|
      start_time = Time.now
      response = HTTParty.get("http://#{resource}/", { timeout: 1 })
      next unless response.body.include?(word)

      status = response.code
      time_string = "(#{((Time.now - start_time) * 1000).round}ms)"

      request = Request.new(uri: resource, status: status, time: time_string)
      requests << request
      print_out(request)
    rescue StandardError => e
      status = "ERROR (#{e})"
    end
```

В данном случае не будут записаны ошибки, он их перескочет.

2021-04-09 10:16 UTC, warkann commented on Mur_Ilya/2/lib/request_collector.rb
> +      begin
логика запроса должна лежать в отдельном методе, где ты можешь использовать `rescue...ensure`. Используя новый метод ты можешь получать статусы внутри итерации в любом виде, который тебе нужен. Но тогда основной метод нужно переименовать, потому что метод сейчас у тебя отвечает не только за посылку запроса (что-то например `process_request`)

2021-06-16 10:40 UTC, closed without merging