Hw 2 4
rubyroidlabs/hexlet-2021 pull request #44
Opened 2021-04-14 14:11 UTC by Yorickov

## Фамилия Имя
Иванов Петр

## Email
foo@bar.com

## Номер домашнего задания
1

## Ссылка на видео с демо работы
https://www.youtube.com/watch?v=ecIWPzGEbFc

## Комментарии
Хотел сделать то-то, но не успел и не понимаю.

2021-04-14 16:01 UTC, kolbaA requested changes

2021-04-14 16:01 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/http_service.rb
> +    # rubocop:disable Rails::TimeZone
rubocop:disable Rails/TimeZone ?

2021-04-14 16:01 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/filter.rb
> +      # rubocop:disable Style/SlicingWithRange -- [n..] -> Syntax Error
почему выключил эти проверки? 
Пофикси их пожалуйста

2021-04-14 16:12 UTC, Yorickov commented on Dzmitry-Monich/2/checker/lib/checker/filter.rb
> +      # rubocop:disable Style/SlicingWithRange -- [n..] -> Syntax Error
> почему выключил эти проверки?
> Пофикси их пожалуйста

ок, у меня почему-то [n..] выдает Syntax error, пока не разбирался - закомментил чтобы рубокоп по-быстрому проверть

2021-04-14 18:30 UTC, Yorickov commented on Dzmitry-Monich/2/checker/lib/checker/http_service.rb
> +    # rubocop:disable Rails::TimeZone
fixed

2021-04-19 15:55 UTC, kolbaA requested changes
Пока что первая часть моего ревью. 
Хотелось бы как минимум еще увидеть рефакторинг классов `Filter` и `Printer` 
Завтра посмотрю как лучше сделать. Если что-то не понятно пингуй в слаке или здесь 😉

2021-04-19 15:55 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/application.rb
> +    def call(filepath)
Обычно метод `call` в объекте типа сервис(имею в виду ServiceObject) не принимает параметров а использует параметры из `initialize`.
Поэтому предлагаю вынести параметр `file_path` в initialize и добавить его в attr_reader

2021-04-19 15:55 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/application.rb
> +      keys = options.select { |_k, v| v == true }.keys
Почему бы не вынести это в  класс `Filter` ? по ощущениям именно он ответственен  чтобы что-то отфильтровать согласно тому, какие options есть у нас

2021-04-19 15:55 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/application.rb
> +      filtered_links = filter_links(links)
Если вынести `options.select { |_k, v| v == true }.keys` в класс `Filter` как я написал ниже, то тут уже получится что-то аля

`filtered_links = Filter.new(links, options).call`

2021-04-19 15:55 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/application.rb
> +      responses = http_responses(filtered_links)
Аналогично можно убрать метод `http_responses` и написать

`HttpService.new.call(links, options[:parallel])`

2021-04-19 15:55 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/application.rb
> +    def filter_urls(responses)
Непонятно по неймингу здесь. 
Выше ты фильтровал ссылки, сейчас фильтруешь урлы. А в чем разница? При этом в этом методе у тебя фигурируют `responses`. Ты наверное тут делаешь какой-то фильтр объектов которые тебе вернул `HttpService` ? 
Тогда, возможно, будет логично назвать этот метод `filter_responses`. 
Вообще, я больше за то чтобы его убрать и вынести проверку наличия фильтра в класс `Filter`

2021-04-19 15:55 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/parser.rb
> +        raise 'no such a parser' unless parcers.key?(type)
поменяй везде текст с `no such a ${smth}` на `no such ${smth}` (удали  `a`) пожалуйста

2021-04-19 15:55 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/parser.rb
> +      def parse(filepath)
можно поменять на `call` а нижний метод `parcers` на `parsers` это будет более правильно мне кажется и без всяких специальных ошибок в словах 
что думаешь?

2021-04-19 16:46 UTC, Yorickov commented on Dzmitry-Monich/2/checker/lib/checker/parser.rb
> +      def parse(filepath)
Ничего специального тут нет, иногда ошибки - это просто ошибки:))
Я тут тоже думал передать путь в конструктор, но совсем мало логики в классе - оставлю так. Переименую call в parse, т.к. аргумент он получает

2021-04-19 20:29 UTC, Yorickov commented on Dzmitry-Monich/2/checker/lib/checker/parser.rb
> +      def parse(filepath)
Пофиксил все, Parser менять в соотв. с ServiceObject жалко - мало логики, но если надо - поменяю.

Вопрос по Printer: сначала у меня был другой вариант реализации - вместо OpenStruct использовать обычный объект и добавить ему в to_s логику вывода (с разной реализацией для двух типов Ответа), тогда бы Printer сильно ужался. Но посколько в нем какая-то логика вывода все равно бы оставалась - решил ее не делить, и оставил всю в Принтере. Как более правильно?

2021-04-20 18:20 UTC, kolbaA requested changes
До конца просмотреть тесты не хватило меня
Нужно их конечно тоже переделать в идеале)

2021-04-20 18:20 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/printer.rb
> +        result = calc_total(responses)
c учетом рефакторинга выше можно убрать result = calc_total(responses)
и получится
```
  [
          "Total: #{total_result[:total]}",
          "Success: #{total_result[:success]}",
          "Failed: #{total_result[:failed]}",
          "Errored: #{total_result[:errored]}"
        ].join(', ')
```

2021-04-20 18:20 UTC, kolbaA commented on Dzmitry-Monich/2/checker/spec/checker/application_spec.rb
> +  subject { Checker::Application }
subject { Checker::Application.new(filepath, parallel: parallel) }
тогда  не придется везде писать 
`expect(subject.new(args).call`
а для parallel можно сделать 2 контекста
```
  context 'in one thread' do
    let(:parallel) { nil }
     
    it 'runs correctly' do
       ... 
    end
  end
  context 'in parallel threads' do
    let(:parallel) { 5 }

   it 'runs correctly' do
       ... 
   end
  end
```

2021-04-20 18:20 UTC, kolbaA commented on Dzmitry-Monich/2/checker/spec/checker/application_spec.rb
> +    it 'file not exists' do
соответсвенно `file not exists` и `parser not exists (wrong file extention)` тоже лучше сделать через контексы, в которыых у тебя `let(:filename) { }` будет меняться, а название экзамла(блок it) будет выглядеть типо `it 'raises error'`

2021-04-20 19:48 UTC, Yorickov commented on Dzmitry-Monich/2/checker/lib/checker/printer.rb
> +      def print(responses)
о нет, так слишком неявно - сделаю по классике с конструктором. У меня вечно с ним проблема - когда нужен, а когда нет, но сейчас вроде пояснее

2021-04-20 19:49 UTC, kolbaA commented
Ссылка на видео не работает, добавь пожалуйста 😄

2021-04-20 19:52 UTC, kolbaA commented on Dzmitry-Monich/2/checker/lib/checker/printer.rb
> +      def print(responses)
@Yorickov вообще я бы так посоветовал. Если у тебя в класс не надо передавать аргументы, то initialize не нужен. в Остальных случаях не ошибешься)

2021-04-20 20:16 UTC, Yorickov commented on Dzmitry-Monich/2/checker/lib/checker/printer.rb
> +        result = calc_total(responses)
а вот это очень круто с кэшированием

2021-04-20 20:51 UTC, Yorickov commented on Dzmitry-Monich/2/checker/lib/checker/application.rb
> +      validate(filepath)
Убрать параметр у `validate` не могу - он проверяет `absolute_path`, а добавить в конструктор еще и его - уже перебор:)

2021-04-20 21:18 UTC, Yorickov commented on Dzmitry-Monich/2/checker/spec/checker/application_spec.rb
> +    it 'file not exists' do
Все пофиксил

2021-04-20 23:05 UTC, Yorickov commented on Dzmitry-Monich/2/checker/lib/checker/printer.rb
> +           fn: ->(res) { "#{res.url} - ERROR (#{res.message})" } }]
над этим завтра подумаю, хотя я не люблю мини классы)

2021-04-22 20:41 UTC, kolbaA approved these changes

2021-04-22 20:41 UTC, merged