solve homework 2
rubyroidlabs/hexlet-2021 pull request #45
Opened 2021-04-19 08:03 UTC by Dein1

## Фамилия Имя
Абрамов Дмитрий

## Email
alpha.ru@gmail.com

## Номер домашнего задания
2

## Ссылка на видео с демо работы
https://asciinema.org/a/1SFFacWibU43LPqzdBXe7flwD

2021-04-19 08:05 UTC, Dein1 commented
Что за коммент от хаунда такой - я не понимаю (

2021-04-19 08:38 UTC, Dein1 commented on Dmitriy_Abramov/2/checker/spec/spec_helper.rb
> +  original_stdout = $stdout
тут я замьютил stdout в тестах - не уверен, что так хорошо делать )

2021-04-19 10:04 UTC, kolbaA commented
> Что за коммент от хаунда такой - я не понимаю (

проигнорь пока
это он ругается на конфиг reek'a

2021-04-20 19:34 UTC, kolbaA requested changes
Пока так...
Завтра продолжу ревью, очень хочется тут навести порядок)

2021-04-20 19:34 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/lib/checker.rb
> +# frozen_string_literal: true
в руби обычно имя файла совпадает с именем класса

2021-04-20 19:34 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/lib/checker.rb
> +        process_requests_parallel(@options[:parallel])
Я думаю аргумент `@options[:parallel]` здесь не нужен. У тебя же есть к нему в этом классе

2021-04-20 19:34 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/lib/checker/request.rb
> +class Request
тут потерялся `module Checker`

2021-04-20 19:34 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/lib/checker.rb
> +      load_hosts
перенеси это для начала в метод `run` слишком много делает метод для того чтобы быть в `initialize`

2021-04-20 19:34 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/lib/checker.rb
> +    end
хотелось бы все это видеть в отдельном сервисе)

2021-04-22 20:36 UTC, kolbaA requested changes

2021-04-22 20:36 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/lib/checker/request.rb
> +      perform
И все таки делать выполнение основной логики в `initialize` неправильно. Во первых это неочевидно, во вторых сложнее тестировать.
Давай сделаем метод `perform` публичным и будем дергать его

2021-04-22 20:36 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/spec/app_spec.rb
> +describe Checker do
тут должно быть Checker::App
и тогда во всех `subject` надо писать `described_class.new(...)`

2021-04-22 20:36 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/spec/app_spec.rb
> +  describe 'invalid file' do
замени describe на context, обычно в describe пишут имя метода или класса. и как раз таки invalid file - это своего рода контекст в котором находится described_class.
Контексты кстати мможно вкладыать друг в друга)
ну и + 
если у тебя есть контекст `invalid file` - то по логике где-то должен быть и `valid_file` )

2021-04-22 21:22 UTC, Dein1 commented on Dmitriy_Abramov/2/checker/lib/app.rb
> +      @requests = Hash.new { |hash, key| hash[key] = [] }
Я не смог найти, как по другому сделать дефолтное значение для ключа. Это нужно, чтобы сработала строка: ``` @requests[request.status] += [request]```

Ну либо хэш для реквестов сделать таким: ```@requests = {success: [], failed: [], error: []}```

2021-04-26 17:40 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/lib/checker/filter_service.rb
> +      (host_name_arr.size >= 3) || (host_name_arr.size == 3 && host_name_arr.first != 'www')
Хорошая практика выносить магические числа в константы. Типа `SUBDOMAIN_SIZE_LIMIT = 3`

2021-04-26 17:45 UTC, kolbaA commented on Dmitriy_Abramov/2/checker/spec/filter_service_spec.rb
> +  describe 'without filters' do
обычно в describe оборачивают имя метода который тестируется, т.е 
```
describe '#filter_hosts' do
  context 'without filters' do
     ...
  end
  ....
end
```
и тож самое для метода `selected_content?`

2021-04-26 17:47 UTC, kolbaA approved these changes
В принципе код хорошо читается и сделано просто)
Харош 💪

2021-04-29 07:41 UTC, merged