Pavel_MIkhaylov - 2
rubyroidlabs/hexlet-2021 pull request #48
Opened 2021-04-19 15:59 UTC by badta5te

## Фамилия Имя
Михайлов Павел

## Email
mikhailov.sztu@gmail.com

## Номер домашнего задания
2

## Ссылка на видео с демо работы
[![asciicast](https://asciinema.org/a/pWncVSLgPeovIrQkpptDMEeb9.svg)](https://asciinema.org/a/pWncVSLgPeovIrQkpptDMEeb9)

## Комментарии
Только начал вникать в тесты, не успел покрыть все приложение. В дальнейшем сделаю это.

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/bin/checker
> +#!/usr/bin/env ruby
Почему ты не использовал `.rb` файл?

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/bin/checker
> +#!/usr/bin/env ruby
Если этот файл переименовать в  `main` - будет ли это более информативнее, привычние и уберет дублирование имен? Как считаешь?

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/csv_reader.rb
> +  attr_reader :data
Как ты решал где использовать `attr_reader`? в классе `Checker` его нет, а тут есть?

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/csv_reader.rb
> +  end
я бы сделал немного по-другому. 
Метод `initialize` обычно не используют, чтобы сделать в нем всю работу. Тут скорее нужно инициализировать объект, сохранить `path`, а потом на экземпляре вызвать метод, который и будет выполнять работу.

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +    if !@options.key?(:subdomains) && !@options.key?(:solutions)
у тебя тут два отрицательных условия, я бы рекомендовал использовать `unless`. Но в твоем случае, выглядит как-будто тебе нужно операции местами поменять и можно будет нормально использовать условие.

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +      opensources.find { |res| row.include?(res) }
Ты уверен, что тут нужно использовать `.find`? Он найдет первое значение которое удовлетворяет условию, а тебе вроде нужен `.filter`

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +      result << fetch(url) unless fetch(url).nil?
похоже что тут у тебя выполнение метода `.fetch` происходит два раза - один раз в условии и второй раз в выполнении

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +      return unless response.body.include?(@search_word)
я правильно понимаю, что у тебя будет это условие работать даже если я не указал опцию фильтрации по слову?

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/printer.rb
> +        if code >= 200 && code < 400
как тебе `code.between?(200,400)`?

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/printer.rb
> +  end
выглядит не очень. Отличный кандидат для создания отдельного класса, например `Summary`, где ты элегантно можешь реализовать метод `.to_s` и все остальные.

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/spec/http_service_spec.rb
> +  true
интересный тест ))

2021-04-20 15:32 UTC, warkann commented on Mikhaylov_Pavel/2/spec/csv_reader_spec.rb
> +# frozen_string_literal: true
тестов не очень много и не рассматриваются "отрицательные" сценарии.

2021-04-20 15:52 UTC, badta5te commented on Mikhaylov_Pavel/2/bin/checker
> +#!/usr/bin/env ruby
тут исходил из того, что запуск должен быть через бинарный файл. [вначале](https://github.com/rubyroidlabs/hexlet-2021/pull/48/commits/51bb849084f7a1d844936c9869ff02af877a4732) так и было main.rb и из него весь запуск, но потом переписал

2021-04-20 15:55 UTC, badta5te commented on Mikhaylov_Pavel/2/spec/http_service_spec.rb
> +  true
это зародышь))))) молодой незрелый тест 😂

2021-04-20 17:27 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/csv_reader.rb
> +  attr_reader :data
в случае `csv_reader` мне нужно было получить данные присвоенные переменной инстанса, в остальных классах такой необходимости не было. я из методов возвращал результат, а не присваивал его переменной инстанса и получал доступ к этим данным через геттер.

2021-04-20 17:41 UTC, badta5te commented on Mikhaylov_Pavel/2/spec/csv_reader_spec.rb
> +# frozen_string_literal: true
да, тесты еще в процессе написания и освоения, попробую завтра-послезавтра уже сделать тесты на все классы.

2021-04-20 18:04 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/printer.rb
> +        if code >= 200 && code < 400
✅

2021-04-20 18:08 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +      return unless response.body.include?(@search_word)
да, [тут](https://github.com/badta5te/hexlet-2021/blob/homework2/Mikhaylov_Pavel/2/lib/checker.rb#L29) передаю слово, а в 37-й строке использую `.fetch` с значением по умолчанию `''` для его получения.

2021-04-20 18:22 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +      opensources.find { |res| row.include?(res) }
ну вроде как все работает, или я задаю какие-то не те условия. т.е. если я в test.csv добавляю еще один opensource ресурс, до оба исключаются из выборки

2021-04-20 18:22 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +    if !@options.key?(:subdomains) && !@options.key?(:solutions)
✅

2021-04-20 18:35 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +      result << fetch(url) unless fetch(url).nil?
тут я не придумал как лучше сделать проверку на возврат `nil` из `.fetch`. у меня возвращается `nil` если есть слово фильтрации (25-я строка этого же файла)

2021-04-22 08:22 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/printer.rb
> +  end
задумался, а правильно ли то, что сделал именно класс Summary? Может нужно было сделать модуль? Почитал в интернете, и если правильно понял, то надо делать модуль вместо класса, когда у нас не планируется быть экземпляра этого класса. или неправильно понял мысль?

2021-04-22 15:41 UTC, warkann commented on Mikhaylov_Pavel/2/bin/checker
> +#!/usr/bin/env ruby
круто

2021-04-22 15:45 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/printer.rb
> +  end
Тут единого мнения нет. Модули обычно нужно, чтобы include подмешать функциональность в другой класс либо логически разделить области работы (namespace). В случае с Summary у тебя отдельная сущность, логически выглядит как-будто это должен быть класс со своим initialize и прочим.

2021-04-22 19:36 UTC, warkann requested changes

2021-04-22 19:36 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +    begin
мы можем убрать `begin` потому что объявление метода тоже блок
```
def fetch(url)
  ...
rescue StandardError => e
  ...
ensure
  result
end
```

2021-04-22 19:36 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +      result << fetch(url) unless fetch(url).nil?
тут мы можем убрать `unless fetch(url).nil?` оставив `result << fetch(url)`, а в конце на возвращаемом значении вызвать `result.compact`

2021-04-22 19:36 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +      return unless response.body.include?(@search_word)
понял, при значении '' всегда будет возвращаться true

2021-04-22 19:36 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +      start_time = Time.now.getlocal
тут было не обязательно было использовать `getlocal`, мы же замеряем разницу между стартом и финишем

2021-04-22 19:36 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +    result = []
по-идее мы каждый раз создаем новый объект и могли вынести все `result = []` и ему подобные `initialize`

2021-04-22 19:36 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/printer.rb
> +      end
очень сложно читать и понимать такие конструкции, как тебе такое:
```
if url_data.key?(:code)
  code = url_data[:code]

  @summary[:success] += 1 if code.between?(200, 400)
  @summary[:fail] += 1 if code >= 400
else
  @summary[:error] += 1
end
```

2021-04-22 19:36 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/summary.rb
> +class Summary
в данном случае лучше действительно использовать `module`. Ранее я тебе рассказывал когда лучше использовать модули и тут как раз ситуация, когда мы создаем отдельный namespace

2021-04-22 19:36 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/summary.rb
> +class Summary
сейчас файл выглядит супер, но в реальном приложении вряд ли такое стоит делать, потому что такие классы наверняка разрастутся и нужно будет их разносить по разным файлам.

2021-04-23 07:32 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker.rb
> +    csv_data
это было сделано так, чтобы в bin файле запуск производился одной командой `run`. и уже в ней я собрал вызовы всех необходимых методов

2021-04-23 08:02 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker.rb
> +    csv_data
так метод `csv_data` у тебя ничего по сути не делает. Он инициализирует `CsvReader` в никуда.

2021-04-23 08:04 UTC, warkann commented on Mikhaylov_Pavel/2/bin/checker
> +checker.run
тут будет логичнее сделать ` Checker.new(file, options).run` - мы же ничего с переменной не делаем и особой красоты это не несет

2021-04-23 08:14 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker.rb
> +    csv_data
точно! начал расписывать свою логику такого написания и понял ошибку. перепишу) спасибо

2021-04-23 12:01 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +    begin
попробовал сделать так, но в таком случе, в результате `ensure result` у меня в `result` записывается только данные о времени, причем без ключа. И получается, что в Printer у меня приходит массив из float:
`[0.797242,
 1.931959,
 0.885799,
 0.64908,
 0.157197,
 1.123717,
....]`
как это побороть и почему возникает я не могу понять

2021-04-23 12:04 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +      start_time = Time.now.getlocal
вначале было написано Time.now, но на такую запись ругался рубокоп:
`Rails/TimeZone: Do not use Time.now without zone. Use one of Time.zone.now, Time.current, Time.now.in_time_zone, Time.now.utc, Time.now.getlocal, Time.now.xmlschema, Time.now.iso8601, Time.now.jisx0301, Time.now.rfc3339, Time.now.httpdate, Time.now.to_i, Time.now.to_f instead.`
в итоге пришел к такому варианту

2021-04-23 12:18 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +      start_time = Time.now.getlocal
странное правило, но ок

2021-04-25 11:33 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +    Array.new(@parallel) do
Прикольное решение. Но чаще ты можешь встретить конструкции типа:
```
threads = []
10.times {
  threads << Thread.new { puts 1 }
}
threads.each(&:join)
```

2021-04-25 11:33 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker.rb
> +  end
Как ты думаешь, целесообразно ли вынести эти два метода в `initialize` и добавить `attr_reader :search_word, :parallel `?

2021-04-25 11:33 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker.rb
> +  end
Все ли методы в этом классе должны быть публичными?

2021-04-25 11:33 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +      opensources.find { |res| row.include?(res) }
Так же и должно быть?

2021-04-25 11:33 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker.rb
> +
Все ли методы ниже должны быть публичными?

2021-04-25 11:33 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker.rb
> +    print_out
В будущем такие вещи лучше писать немного по другому. Что делает наш метод? Пойдем по пунктам:

1. Мы фильтруем данные, если нужно
2. Делаем запросы
3. Выводим результат

Если наш метод `.run` имеет такую структуру, то мы с первого взгляда логически понимаем, как оно работает и что делает + дебажить в разы проще.

2021-04-25 11:33 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker.rb
> +  end
Как ты думаешь, имеет ли смысл перенести это в `initialize` и добавить ```attr_reader :search_word, :parallel```

2021-04-25 11:33 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +
Все ли методы тут должны быть публичными?

2021-04-25 11:33 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +    end
Я не совсем понимаю логику тут. Почему мы не можем сделать ```subdomains.flatten! & open_source.flatten!``` в методе выше?

2021-04-26 13:13 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +      opensources.find { |res| row.include?(res) }
да, логика верная

2021-04-26 13:57 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +    Array.new(@parallel) do
ну да, выглядит проще, переписать?

2021-04-26 13:58 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker.rb
> +    print_out
Т.е. лучше не делать отдельные методы на фильтрацию, запросы и вывод, а вызывать все уже из самого метода `run`?

2021-04-26 14:07 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +    end
Потому что тут я делал пересечение множеств, соот-но, если у меня нет какого-то из ключей (:subdomains или :solutions), то один из массивов (строки 18 и 19) будет пустым, соот-но и пересечение множеств будет пустым массивом.
В итоге пришлось делать такую проверку, что если один из массивов (18 и 19 строки) пустой, то возвращаем другой. Как это упростить и сделать чтобы у меня корректно применялись оба фильтра я не придумал в момент написания, да и сейчас нет идей

2021-04-26 14:09 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +
внес корректировки

2021-04-26 14:24 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker.rb
> +  end
методы поменял, а по поводу переноса в `initialize`, не могу дать четкого ответа, на мой взгляд не много разницы, таким образом немного увеличится `initialize`, но уйдут 2 метода. Но с другой стороны мои методы это по сути те же геттеры, соот-но можно и использовать их согласно идеи руби через `attr_reader`. перепишу

2021-04-27 00:41 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +    end
ты можешь вернуть из метода `filter_by_options` что то типа
```
[subdomains.flatten, open_source.flatten]
```
согласен?

2021-04-27 00:41 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/http_service.rb
> +    Array.new(@parallel) do
не надо, твоя задумка интересная. Это я просто показал как обычно в продакшн пишут)

2021-04-27 05:20 UTC, badta5te commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +    end
нет, мне же в любом случае надо делать пересечения `subdomains.flatten & open_source.flatten`. Если у меня, например в `subdomains.flatten` не попал url `153.straumann.ntn`, а в результате фильтра по `open_source` он будет присутствовать, то этот url будет в результирующем массиве.

2021-04-29 00:32 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +    end
Да, не обратил внимание, что там & а не &&

2021-05-04 16:51 UTC, warkann commented on Mikhaylov_Pavel/2/lib/checker/filter.rb
> +    end
тут можно было еще так:
```
return filter_by_options if @options.key?(:subdomains) || @options.key?(:solutions)

@data
```

2021-05-04 16:51 UTC, warkann commented on Mikhaylov_Pavel/2/spec/csv_reader_spec.rb
> +    expect(reader_os.data.size).to eq(99)
второй случай не нужен - код у тебя одинаковый для этих случаев.

2021-05-04 16:51 UTC, warkann commented on Mikhaylov_Pavel/2/spec/csv_reader_spec.rb
> +    expect(reader_os.data.size).to eq(99)
что произойдет есть csv будет пустой? твоя программа упадет? стоит ли добавить код чтобы программа не упала? 
тест на такую ситуацию тоже полезен - ты будешь уверерен что твой класс работает при внесении будущих изменений.

2021-05-04 16:51 UTC, warkann commented on Mikhaylov_Pavel/2/spec/filter_spec.rb
> +        expect(filter.apply_filter.size).to_not eq(urls.size)
это строка не нужна, ты в следущей строке проверяешь, что отсутствует как минимум один элемент)

2021-05-04 20:39 UTC, warkann approved these changes

2021-05-04 20:40 UTC, merged