Homework3
rubyroidlabs/hexlet-2021 pull request #61
Opened 2021-06-08 19:07 UTC by badta5te

## Фамилия Имя
Михайлов Павел

## Email
mikhailov.sztu@gmail.com

## Номер домашнего задания
3

## Ссылка на видео с демо работы
https://www.youtube.com/watch?v=BH8pwOYLXPA

## Комментарии
Немного задержался 🤷🏿‍♂️ тесты еще дописываю

2021-06-10 08:51 UTC, Saicheg requested changes

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/.rubocop.yml
> +AllCops:
Не уверен зачем тебе свой отдельный конфиг, в репозитории есть конфиг робокопа общий для всех

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/Makefile
> +run:
Ого, makefile! :D

Вообще принято для таких вещей делать `Procfile`, можешь почитать что за он :)

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/models/user.rb
> +  aasm do
Я бы сказал что отличная идея использовать Enums для состояний как указано в документации:

https://github.com/aasm/aasm#activerecord-enums

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/db/migrate/20210508193356_create_users.rb
> +      t.string :name
тоже не может быть пустым, `null: false`

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/db/migrate/20210508193431_create_words.rb
> +    create_table :words do |t|
Оба поля не могут быть пустыми `null: false`

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/models/user.rb
> +  def new_word
С архитектурной точки зрения, этот код не должен быть здесь. Пользователь вообще никак не связан с тем, чтобы генерировать новые слова. Для этого лучше всего использовать `service objects` которые бы брали пользователя и генерировали слова для него

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/models/user.rb
> +  def finished?
`finished?` - странное название, я бы сказал что `done_for_today?` или что-то в этом роде было более уместно

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/models/user.rb
> +  def need_to_send_reminder?
Вот я бы вообще сделал отдельным классом, который берет пользователей и выбирает тех кому нужно послать запрос. Заодно можно было бы классно его потестировать. 

```
class UsersNeededReminderFinder
  def initialize(users)
    @users = users
  end
  
  def call
     # Logic goes here
   end
end

UsersNeededReminderFinder.new(User.waiting).call
```

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/models/word.rb
> +  has_many :users, through: :learned_words
Все настройки модели должны идти в самом начале. 

https://github.com/rubocop/rails-style-guide#macro-style-methods

Вот тут можно ознакомиться с правильными и каноничным расположением методов в моделях AR

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/main.rb
> +# frozen_string_literal: true
`main.rb` понятно, но обычно прикольней `run.rb`

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/main.rb
> +TOKEN = ENV['TOKEN']
А что будем делать если `TOKEN` не передали? Не стоит забывать про обработку ошибок

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/message_sender.rb
> +
++

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/actions.rb
> +# frozen_string_literal: true
Запомни - никогда не складывай много классов в один файл. Всегда 1 файл - один класс. Иначе это очень сложно находить в работе :)

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/actions.rb
> +  BOT = Telegram::Bot::Api.new(ENV['TOKEN'])
Эту конфигурацию ты уже читал, поэтому призываю ее читать только один раз в одном месте. И передать это как аргумент в класс.

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/actions.rb
> +  class Greeting
Я бы сделал какой-то базовый Base и от него наследовался:

```
modules Actions
  class Greetings < Base
     # Logic goes here
  end
end
```

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/actions.rb
> +    def record_user
Должен быть тоже `record_user!` потому как используется метод с !  под капотом

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/actions.rb
> +      user = User.find_by(telegram_id: message.from.id)
Вот это можно было смело в базовый класс вынести

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/actions.rb
> +  RESPONSES = {
Константа - хорошо, а еще круче это `.yml` файлик который бы прочитался при запуске и не захламлял тут код

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/emoji_list.rb
> +    Unicode::Emoji.list('Smileys & Emotion').each do |_k, v|
Подумай как тут можно использовать `flat_map`

А еще весь этот list очень похож на константу, его надо только один раз посчитать при запуске

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/teacher.rb
> +require 'pry'
Упадет на продакшене :)

2021-06-10 08:51 UTC, Saicheg commented on Mikhaylov_Pavel/3/lib/teacher.rb
> +class Teacher
Название - лайк :)

2021-06-10 11:03 UTC, badta5te commented on Mikhaylov_Pavel/3/models/user.rb
> +  aasm do
прочитал, но не понял, чем это будет лучше в моем случае?

2021-06-10 11:04 UTC, Saicheg commented on Mikhaylov_Pavel/3/models/user.rb
> +  aasm do
1) у них есть классная интеграция
2) у тебя поле хранится не строкой, а цифрой -> быстрее индексы и меньше места в базе данных

2021-06-10 11:11 UTC, badta5te commented on Mikhaylov_Pavel/3/lib/teacher.rb
> +require 'pry'
упадет из-за `require 'pry'`? не знал, но есть еще некоторые штуки которые не подчистил)

2021-06-14 09:13 UTC, badta5te commented on Mikhaylov_Pavel/3/Makefile
> +run:
Почитал, используя procfile мы не завязываемся на приложение heroku? Ведь makefile, вроде как, доступен в unix "из коробки" и можно сразу его использовать без установки каких-то дополнительных приложений.

2021-06-15 21:13 UTC, badta5te commented on Mikhaylov_Pavel/3/lib/emoji_list.rb
> +    Unicode::Emoji.list('Smileys & Emotion').each do |_k, v|
не придумал, но получилось немного упростить до `Unicode::Emoji.list('Smileys & Emotion').values.flatten`

2022-02-22 09:57 UTC, closed without merging